services:
  # Serwis NGINX (proxy odwrotne)
  - type: web
    name: ad-mine-nginx
    runtime: docker
    dockerfilePath: ./nginx/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: TARGET_URL
        value: https://httpbin.org/status/200
      - key: CLICK_RATE
        value: "0.20"
      - key: STRIPE_SECRET
        value: ${STRIPE_SECRET}  # Użyj zmiennych środowiskowych z Render Secrets
      - key: STRIPE_PUBLIC
        value: ${STRIPE_PUBLIC}
      - key: HUG_TOKEN
        value: ${HUG_TOKEN}
      - key: VPN_CONFIG_PATH
        value: /vpnbook/PL134.ovpn
      - key: NGINX_URL
        sync: false  # Nie synchronizuj automatycznie - ustaw ręcznie w Dashboard
        value: https://ad-mine-nginx.onrender.com

  # Worker z Selenium (klikacz)
  - type: worker
    name: ad-mine-clicker
    runtime: docker
    dockerfilePath: ./ai-clicker/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: CLICK_RATE
        value: "0.20"
      - key: NGINX_URL
        value: https://ad-mine-nginx.onrender.com
      - key: HUG_TOKEN
        value: ${HUG_TOKEN}
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: SCREEN_WIDTH
        value: "1920"
      - key: SCREEN_HEIGHT
        value: "1080"
      - key: SCREEN_DEPTH
        value: "24"
    numInstances: 1
    region: frankfurt

  # Serwis API (Flask)
  - type: web
    name: ad-mine-api
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET
        value: ${STRIPE_SECRET}
      - key: STRIPE_PUBLIC
        value: ${STRIPE_PUBLIC}
      - key: HUG_TOKEN
        value: ${HUG_TOKEN}
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000"  # Domyślny port dla Render
